### ISSUE TITLE
Add in better error handling

### ISSUE THREAD

**Issue by takeontom** [takeontom/PyPeri#40]

**Comment by peterfdej** [comment]
HI, when using e.g. get_user_broadcast_history() and user does not exists anymore, you get a crash. I made some mods, in that case it returns a 'unknown'.
Also when you get a connection timeout, it also crashes.
`Traceback (most recent call last):
  File "record_peri.py", line 12, in <module>
    broadcast_history = pp.get_user_broadcast_history(username=user)
  File "C:\python\pyperi.py", line 45, in get_user_broadcast_history
    user_id, username
  File "C:\python\pyperi.py", line 74, in get_web_public_user_session_tokens
    data_store = self._get_web_data_store(user_url)
  File "C:\python\pyperi.py", line 144, in _get_web_data_store
    r = requests.get(url)
  File "C:\Program Files\Python36\lib\site-packages\requests\api.py", line 70, i
n get
    return request('get', url, params=params, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\requests\api.py", line 56, i
n request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\requests\sessions.py", line
488, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files\Python36\lib\site-packages\requests\sessions.py", line
609, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\requests\adapters.py", line
473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', TimeoutError(10060,.......`
[pyperi.zip](https://github.com/takeontom/PyPeri/files/766796/pyperi.zip)

**Comment by takeontom** [comment]
Hi Peter! Awesome, thanks for looking into this.

Any chance you could raise a PR for your changes?

**Comment by peterfdej** [comment]
my mod is quick and dirty. It is just an idea how to solve. You guys can do it better. ;-)

**Comment by peterfdej** [comment]
My testing script.
[https://github.com/peterfdej/record_peri](url)

**Comment by takeontom** [comment]
Thanks for including the your work @peterfdej , helps a lot.

If I try and get user or broadcast details for a non-existent user or broadcast, then I'm not sure I expect to get anything back at all. So will have a look into either returning `None` for missing users/broadcasts, or throwing a new `UserDoesNotExistException`.

**Comment by takeontom** [comment]
@peterfdej I went with returning `None` whenever a user or broadcast is not found.

So it can now be used something like:

```
broadcast_history = pp.get_user_broadcast_history(username=user)
if broadcast_history:
    # Do stuff
```

Have also added a custom exception to make detecting connection errors a little easier. Can be used like:

```
from pyperi import PyPeriConnectionError
...
ok = False
while not ok:
    try:
        broadcast_history = pp.get_user_broadcast_history(username=user)
        ok = True
    except PyPeriConnectionError:
        # Try again
        pass
```
